### ISSUE TITLE
[Feature request] Line colour gradient

### ISSUE THREAD

**Issue by VincentBerthier** [feral-dot-io/leptos-chartistry#3]
Hey,
I’ve been using Charming to generate some plots, but I’m considering switching over. 

A feature I really like with Charming is the ability to create plots where the line colour is a gradient between min and max values.
Something like this:
![image](https://github.com/feral-dot-io/leptos-chartistry/assets/34085617/1ad481bd-4e22-490d-8de9-c078e6814f85)

Would it be possible to get the same kind of thing on Chartistry?

**Comment by feral-dot-io** [comment]
Thanks for the first issue!

I've put together Line::with_gradient that takes a colour scheme. You can pass it a sequential gradient to get what you're after. It can also accept a diverging gradient where it'll put two gradients on either side of a zero value.

This was merged in PR #5 and is good to go. I'll put it in a release next week.

**Comment by feral-dot-io** [comment]
I've put the release out earlier because of #4.

You should see it working in the Line colour scheme example https://feral-dot-io.github.io/leptos-chartistry/examples.html#line-colour-scheme
