### ISSUE TITLE
SSR example issue

### ISSUE THREAD

**Issue by tah-alv** [feral-dot-io/leptos-chartistry#33]
Hi, Thank you for an amazing library.  I'm interested in using `leptos-chartistry` to plot data that is streamed from the server in an SSR app so I was going to use the [SSR example](https://github.com/feral-dot-io/leptos-chartistry/tree/master/examples/ssr) as a starting point.  However, when I try to run this example using stable rust (1.81) with `cargo leptos serve` I get an error similar to that mentioned in #27:

```sh
thread 'main' panicked at /home/tah/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-0.2.93/src/lib.rs:1021:1:
function not implemented on non-wasm32 targets
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
```

`cargo leptos build` completes without any errors though.  Are there any other instructions needed to run the SSR example in the repo, or in general to use `leptos-chartistry` in an SSR app (e.g. need leptos 0.7, or the nightly compiler)?  Issue #27 mentioned an "SSR feature flag that makes SSR usage sane" but I'm not sure if that's a clue or not.

Thank you!

**Comment by feral-dot-io** [comment]
Thanks for this. I was able to reproduce the error and found the leptos-use dependency in the example was out of sync with the main. So a quick update from 0.12 to 0.13 fixed the panic.
