### ISSUE TITLE
Leptos 0.7 support

### ISSUE THREAD

**Issue by avsaase** [feral-dot-io/leptos-chartistry#34]
Hi, thanks for making this awesome crate.

Leptos is working towards a 0.7 release with rc1 currently available. As I understand it, no more breaking changes are expected before the final release. 

It would be cool if leptos-chartistry is updated with support with 0.7. I can understand if you don't want to make releases to support leptos release candidate versions because cargo doesn't consider them compatible so you'd have to make a new release for every `leptos` release candidate. A git branch that can be locally updated to the correct leptos version would already be usable IMO. leptos-use has a an version 0.14.0-rc3 compatible with the leptos so that's not a blocker.

There are a number of breaking changes but it doesn't seem too bad overall. I took a stab at doing the update myself but I'm a relative leptos beginner and not familiar with the leptos-chartistry internals so I may not be the best person to tackle this.

**Comment by feral-dot-io** [comment]
I'm glad you like it :)

The 0.7 is planned and the current status of things can be found on the `leptos_0_7` branch. I've been bitten by compile times on the demo site and no docs.rs makes it harder to confidently do a pre-release. There's also the `leptos_0_7_erasure` branch that did address compile times but it's pinned to a beta release.

**Comment by feral-dot-io** [comment]
Version 0.2.0 has landed with support for Leptos 0.7. Let me know if you run into problems with it.
