### ISSUE TITLE
Dynamically Toogle/Add/Remove metric to in chart and modify visualisation style (bar/line/etc..)

### ISSUE THREAD

**Issue by micharambou** [feral-dot-io/leptos-chartistry#36]
Hi!
Im looking for an example how to achive this:

Assuming a dataset corresponding of mutliple metrics (e.g. metric A, metric B, metric C):
How to dynamically toogle/add/remove one or multiple metrics within one chart and/or it's visualisation style within one chart

For example by user interaction in a form:

| | Metric A | Metric B | Metric C |
|-|---|---|---|
|axis | [ x ] y1  [   ] y2  [  ] none | [ x ] y1  [   ] y2  [  ] none | [  ] y1  [  ] y2  [ x ] none
| style | [ x ] **bar** [   ]  line | [   ]  bar [ x ]  **line** | [ x ]  **bar** [   ]  line | 

Thanks in advance

**Comment by feral-dot-io** [comment]
Chartistry lacks fine-grained reactivity on the series so you'd need to wrap it in a signal and re-render the whole chart when you add or remove metrics or change their style. This is a shortcoming as it should be fine-grained everywhere.

For the axis, if I understand you correctly then the idea is that you stop feeding them data and then they "collapse" to zero. So for example the RotatedLabel with an empty "" text will stop taking up any space. This probably should be replaced with an `enable: RwSignal<bool>` on the edge layouts.

So in your case you would likely be wrapping the call to `<Chart>` with a signal and re-rendering the whole thing when it changes. This is non-ideal but not terribly inefficient as it would likely be re-rendering a lot on the page already.

I'm going to close this issue as, while it's clear there are API improvements to be made, I'm already aware of them from a high-level perspective.
